name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v3
    - name: pip cache
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: pip install -r ./requirements.txt
    - run: yarn run lint --if-present
    - run: yarn test
    - run: yarn run build --if-present
      env:
        CI: true
